

[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/jobs/:id"
  to = "/jobs/template.html?id=:id"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/php-server"
  status = 200