[build]
  functions = "netlify/functions"

[build.environment]
  MONGO_URI = "mongodb+srv://admin:fredfred123@lx-tech.zoryjvs.mongodb.net/"

[dev]
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-functions-installation"