[[redirects]]
  from = "/*"
  to = "404/404.html"
  status = 404

[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200